-- SQLite Schema for AI User Interface Core Interaction Tables

-- 1. Models Table
-- Stores configurations for different AI models used (e.g., 'gemini-2.5-flash').
CREATE TABLE Models (
    model_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    context_window_size INTEGER,
    active BOOLEAN NOT NULL DEFAULT 1,
    -- Additional fields for custom models
    api_key TEXT,
    provider TEXT,
    system_instruction TEXT,
    is_custom BOOLEAN DEFAULT 0
);

-- Initialize with a common default model
INSERT INTO Models (name, description, context_window_size) VALUES
('gemini-2.5-flash-preview-09-2025', 'Google''s fast and versatile model.', 1000000);

-- 2. Conversations Table
-- Stores metadata for each unique chat session or thread.
CREATE TABLE Conversations (
    conversation_id INTEGER PRIMARY KEY,
    -- Title generated by the AI or set by the user (can be NULL initially)
    title TEXT,
    -- Link to the specific AI model used for this conversation
    model_id INTEGER NOT NULL,
    -- Timestamps for creation and last update
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    FOREIGN KEY (model_id) REFERENCES Models(model_id)
);

-- Create a trigger to automatically update the 'updated_at' column on every conversation modification
CREATE TRIGGER update_conversations_updated_at
AFTER UPDATE ON Conversations
FOR EACH ROW
BEGIN
    UPDATE Conversations SET updated_at = CURRENT_TIMESTAMP WHERE conversation_id = NEW.conversation_id;
END;

-- 3. Messages Table
-- Stores the actual content of the messages (prompts and responses) within a conversation.
CREATE TABLE Messages (
    message_id INTEGER PRIMARY KEY,
    -- Link back to the conversation thread
    conversation_id INTEGER NOT NULL,
    -- The role of the speaker: 'user', 'assistant', or 'system'
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'system')),
    -- The main text content of the message
    content TEXT NOT NULL,
    -- Order of the message within the conversation (1, 2, 3, ...)
    message_order INTEGER NOT NULL,
    -- The time the message was recorded
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- Estimated token count for billing/context tracking purposes
    token_count INTEGER,
    
    FOREIGN KEY (conversation_id) REFERENCES Conversations(conversation_id) ON DELETE CASCADE
);

-- Ensure that the combination of conversation_id and message_order is unique
CREATE UNIQUE INDEX idx_message_order ON Messages (conversation_id, message_order);
